# version: '3.8' -> it is deprecated now

services:
  nextjs:
    build: .
    container_name: nextjs_app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - nextjs_network

networks:
  nextjs_network:
    driver: bridge
