name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev # Run tests only on PRs targeting dev
  push:
    branches:
      - main # Deploy only on pushes to main

jobs:
  test:
    name: Run Tests
    if: github.event_name == 'pull_request' # Ensures tests only run on PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Prettier Check
        run: npx prettier --check .

      # - name: Run Linter
      #   run: npm run lint

      # We'll add more test later
      # - name: Run Tests
      #   run: npm test
