name: Deploy Next.js App

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted #ubuntu-latest if you don't run runner on vps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Start Containers
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Clean up unused images
        run: |
          docker image prune -af
